"""One-off seeding script: ingest hand-edited past resumes into content_memory.

Walks the .docx files in ``resume/``, parses the structured sections (the docx
was generated by this app's docx_builder so the layout is predictable),
matches research-entry titles back to accomplishment IDs in
``docs/profile_complete.yaml``, and writes:

  1. A synthetic ``Document`` row per resume (job_id=NULL, source preserved
     in ``content_docx_path``).
  2. ``content_memory`` rows: one ``research_description`` per matched
     accomplishment, one ``experience_bullets_set`` per employer, one
     ``skill_bucket`` per non-empty bucket, plus ``summary`` / ``tagline``.

Designed to run once via:
    docker compose exec api python scripts/ingest_past_resumes.py

Idempotent on the unique key (entity_type, entity_key, source_doc_id) — but
re-running creates new ``Document`` rows each time, so prefer to run once.
"""

from __future__ import annotations

import asyncio
import logging
import os
import re
import sys
import uuid
from pathlib import Path
from typing import Any

# Make ``app`` importable when run via ``python scripts/ingest_past_resumes.py``
ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from docx import Document as DocxDocument  # noqa: E402
from sqlalchemy import select  # noqa: E402

from app.ai.utils import employer_key as employer_key_fn  # noqa: E402
from app.database import async_session  # noqa: E402
from app.models import ContentMemory, DocType, Document, UserProfile  # noqa: E402
from app.services import content_memory_service  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("ingest_past_resumes")


# Inside the api container the repo's `resume/` is mounted at /app/resume.
# When run from the host (backend/ as ROOT), it lives at ROOT.parent/resume.
_resume_candidates = [Path("/app/resume"), ROOT.parent / "resume"]
RESUME_DIR = next((p for p in _resume_candidates if p.is_dir()), _resume_candidates[0])

# Section headers (uppercased) emitted by docx_builder._add_section_header.
_HEADER_SUMMARY = "SUMMARY"
_HEADER_RESEARCH = "SELECTED RESEARCH"
_HEADER_EXPERIENCE = "PROFESSIONAL EXPERIENCE"
_HEADER_PUBLICATIONS = "SELECTED PUBLICATIONS"
_HEADER_SKILLS = "TECHNICAL SKILLS"
_HEADER_EDUCATION = "EDUCATION"
_HEADER_AWARDS = "AWARDS & HONORS"

_ALL_HEADERS = {
    _HEADER_SUMMARY,
    _HEADER_RESEARCH,
    _HEADER_EXPERIENCE,
    _HEADER_PUBLICATIONS,
    _HEADER_SKILLS,
    _HEADER_EDUCATION,
    _HEADER_AWARDS,
}

_BULLET_PREFIX = "•"  # • that docx_builder emits as the bullet glyph


# ---------------------------------------------------------------------------
# Filename → (company, title) parser
# ---------------------------------------------------------------------------

# Filename pattern is "{Name} {Company} {Title}.docx" or
# "{Last}_{First}_{Company}_{Title}.docx". The owner name and any
# multi-word companies are derived from profile_data at runtime, so this
# script works for any user — not just whoever wrote it.

_FILENAME_PATTERN_TEMPLATES = (
    # "{Name} {Company} {Title}.docx"
    r"^{name} (?P<company>.+?) (?P<title>.+?)\.docx$",
    # "{Name} {Company}, {Title}.docx" — comma after company
    r"^{name} (?P<company>[^,]+?), (?P<title>.+?)\.docx$",
    # "{Last}_{First}_{Company}_{Title}.docx"
    r"^{last}_{first}_(?P<company>[^_]+)_(?P<title>.+?)\.docx$",
    # "{Name with underscores}_Resume_{Title}.docx" — fallback for older formats
    r"^{name_underscored}_Resume_(?P<title>.+?)(?:\s\(\d+\))?\.docx$",
)


def _build_filename_patterns(name: str) -> list:
    """Compile filename regexes parameterized on the user's name."""
    parts = name.strip().split()
    if not parts:
        return []
    first = parts[0]
    last = parts[-1] if len(parts) > 1 else ""
    name_underscored = "_".join(parts)
    name_escaped = re.escape(name)

    patterns: list = []
    for tmpl in _FILENAME_PATTERN_TEMPLATES:
        try:
            rendered = tmpl.format(
                name=name_escaped,
                first=re.escape(first),
                last=re.escape(last),
                name_underscored=re.escape(name_underscored),
            )
            patterns.append(re.compile(rendered))
        except (re.error, IndexError):
            continue
    return patterns


def parse_filename(
    filename: str,
    *,
    owner_name: str,
    multiword_companies: tuple[str, ...] = (),
) -> tuple[str, str]:
    """Extract (company, title) from a tailored-resume filename.

    ``owner_name`` is the resume owner's full name (taken from profile_data).
    ``multiword_companies`` is an optional list of known multi-word company
    names that the simple regex would otherwise truncate to the first word.
    """
    # Try multi-word companies first so "Lila Sciences..." doesn't truncate to "Lila"
    for company in multiword_companies:
        prefix = f"{owner_name} {company} "
        if filename.startswith(prefix):
            title = filename[len(prefix) :].removesuffix(".docx").strip().replace("_", " ")
            return company, _clean_title_artifact(title)

    for pat in _build_filename_patterns(owner_name):
        m = pat.match(filename)
        if m:
            company = (m.groupdict().get("company") or "").strip().rstrip(",.")
            raw_title = (m.groupdict().get("title") or "").strip().replace("_", " ")
            return company, _clean_title_artifact(raw_title)

    stem = filename.removesuffix(".docx")
    return "", stem


def _clean_title_artifact(title: str) -> str:
    title = re.sub(r"\s+\(\d+\)$", "", title)
    return title.lstrip("- ").strip()


# ---------------------------------------------------------------------------
# .docx parser — relies on the layout produced by app.ai.docx_builder
# ---------------------------------------------------------------------------


def parse_docx(path: Path) -> dict:
    """Walk paragraph text, segment by section header, return structured dict.

    Tagline is the centered paragraph immediately after the name. Sections
    follow a simple linear layout (no tables, no nested elements).
    """
    doc = DocxDocument(str(path))
    paragraphs: list[str] = [p.text for p in doc.paragraphs]

    out = {
        "tagline": "",
        "summary": "",
        "selected_research": [],
        "experience": {},  # display_name → list[bullet_text]
        "technical_skills": {},
        "awards": "",
    }

    # Find the tagline: first non-empty paragraph after the name (which is
    # all-uppercase, contains spaces, and is short).
    name_idx = None
    for i, txt in enumerate(paragraphs):
        stripped = (txt or "").strip()
        if not stripped:
            continue
        # The name paragraph is "PRATEEK PURI" (or similar uppercase).
        if stripped.isupper() and "PURI" in stripped:
            name_idx = i
            break
    if name_idx is not None:
        for j in range(name_idx + 1, min(name_idx + 6, len(paragraphs))):
            tagline = (paragraphs[j] or "").strip()
            if tagline and " · " in tagline:
                out["tagline"] = tagline
                break
            # Some resumes use other separators; accept any short non-empty
            # line that doesn't look like a header or contact info.
            if (
                tagline
                and tagline.upper() not in _ALL_HEADERS
                and "@" not in tagline
                and "linkedin" not in tagline.lower()
            ):
                out["tagline"] = tagline
                break

    # Walk sections.
    current_header: str | None = None
    cur_research: dict | None = None
    cur_employer: str | None = None
    summary_lines: list[str] = []
    awards_lines: list[str] = []

    def commit_research():
        nonlocal cur_research
        if cur_research and (cur_research.get("title") or cur_research.get("description")):
            out["selected_research"].append(cur_research)
        cur_research = None

    for raw in paragraphs:
        text = (raw or "").strip()
        if not text:
            continue
        upper = text.upper()
        if upper in _ALL_HEADERS:
            # Closing whatever was open
            commit_research()
            current_header = upper
            cur_employer = None
            continue

        if current_header == _HEADER_SUMMARY:
            summary_lines.append(text)
            continue

        if current_header == _HEADER_RESEARCH:
            # Format: "{LABEL} — {Title}" with em-dash separator, then
            # a description paragraph below it.
            if " — " in text and (cur_research is None or cur_research.get("description")):
                # New entry
                commit_research()
                label, _, title = text.partition(" — ")
                cur_research = {
                    "category_label": label.strip(),
                    "title": title.strip(),
                    "description": "",
                }
            elif cur_research is not None and not cur_research.get("description"):
                cur_research["description"] = text
            else:
                # Trailing/extra paragraph — append to current description
                if cur_research is not None:
                    cur_research["description"] = (
                        (cur_research.get("description") or "") + " " + text
                    ).strip()
            continue

        if current_header == _HEADER_EXPERIENCE:
            if text.startswith(_BULLET_PREFIX):
                bullet_text = text.lstrip(_BULLET_PREFIX).strip()
                # docx_builder uses "•  " (bullet + two spaces) — strip that
                if cur_employer is None:
                    # Stray bullet before any employer header — skip
                    continue
                out["experience"].setdefault(cur_employer, []).append(bullet_text)
                continue
            # Employer header line: "Org  —  Location" (two-space em-dash separator)
            if "  —  " in text:
                org, _, _location = text.partition("  —  ")
                cur_employer = org.strip()
                out["experience"].setdefault(cur_employer, [])
                continue
            # Title/dates line: "Title  |  Dates" — ignore
            if "  |  " in text:
                continue
            # Anything else under experience — ignore
            continue

        if current_header == _HEADER_SKILLS:
            # Format: "AI Systems: <value>" / "Data Science: <value>" / "Engineering: <value>"
            for label, key in (
                ("AI Systems:", "ai_systems"),
                ("Data Science:", "data_science"),
                ("Engineering:", "engineering"),
            ):
                if text.startswith(label):
                    value = text[len(label) :].strip()
                    if value:
                        out["technical_skills"][key] = value
                    break
            continue

        if current_header == _HEADER_AWARDS:
            awards_lines.append(text)
            continue

        # Other sections (publications, education) — skip in v1.

    commit_research()
    out["summary"] = " ".join(summary_lines).strip()
    out["awards"] = " ".join(awards_lines).strip()
    return out


# ---------------------------------------------------------------------------
# Accomplishment matching
# ---------------------------------------------------------------------------


_STOPWORDS = {
    "a",
    "an",
    "the",
    "of",
    "and",
    "or",
    "for",
    "to",
    "in",
    "with",
    "on",
    "by",
    "at",
    "from",
    "as",
    "is",
    "are",
    "was",
    "were",
    "be",
    "this",
}


def _tokens(text: str) -> set[str]:
    text = re.sub(r"[^\w\s]", " ", text.lower())
    return {t for t in text.split() if t and t not in _STOPWORDS}


def match_accomplishment_id(title: str, catalog: list[dict]) -> str | None:
    """Pick the best-matching accomplishment_id by token overlap with title.

    Falls back to None if the best match is too weak (overlap < 0.3) — the
    research entry will be skipped rather than misattributed.
    """
    title_tokens = _tokens(title)
    if not title_tokens:
        return None
    best_id: str | None = None
    best_score = 0.0
    for a in catalog:
        a_id = a.get("id")
        a_title = a.get("title") or ""
        impact = a.get("impact_summary") or ""
        candidate_tokens = _tokens(a_title) | _tokens(impact)
        if not candidate_tokens:
            continue
        overlap = len(title_tokens & candidate_tokens) / len(title_tokens)
        # Bonus when the accomplishment title's own tokens are mostly covered
        coverage = (
            len(title_tokens & candidate_tokens) / len(candidate_tokens)
            if candidate_tokens
            else 0.0
        )
        score = overlap * 0.7 + coverage * 0.3
        if score > best_score:
            best_score = score
            best_id = a_id
    return best_id if best_score >= 0.3 else None


# ---------------------------------------------------------------------------
# Database writer
# ---------------------------------------------------------------------------


async def ingest_one(session, *, docx_path: Path, profile_data: dict) -> dict | None:
    """Parse one .docx and write the corresponding rows. Returns a stats dict.

    Returns None if the document doesn't follow the app's layout (no
    structured research or experience found).
    """
    parsed = parse_docx(docx_path)

    owner_name = (profile_data.get("personal") or {}).get("name") or ""
    # Multi-word companies that would otherwise be truncated by the regex.
    # Auto-derive from the user's work_history so this works for any user;
    # callers can also extend via the env var INGEST_MULTIWORD_COMPANIES
    # (comma-separated) for companies referenced by past resumes that aren't
    # in the current work_history.
    work_companies = tuple(
        wh.get("employer", "")
        for wh in (profile_data.get("work_history") or [])
        if wh.get("employer") and " " in wh.get("employer", "")
    )
    env_extras = tuple(
        c.strip() for c in os.environ.get("INGEST_MULTIWORD_COMPANIES", "").split(",") if c.strip()
    )
    multiword = work_companies + env_extras

    company, title = parse_filename(
        docx_path.name,
        owner_name=owner_name,
        multiword_companies=multiword,
    )

    # Sanity check: if we couldn't extract any research entries AND no
    # employer headers, the document isn't using docx_builder's layout —
    # skip rather than write a malformed Document.
    if not parsed["selected_research"] and not parsed["experience"]:
        logger.warning(
            "SKIP %s — couldn't parse structured sections (likely older layout)",
            docx_path.name,
        )
        return None

    catalog = (profile_data.get("complete_profile") or {}).get("accomplishments") or []

    # Match research entries → accomplishment_ids; drop unmatched
    research_with_ids: list[dict] = []
    unmatched: list[str] = []
    for entry in parsed["selected_research"]:
        aid = match_accomplishment_id(entry.get("title", ""), catalog)
        if not aid:
            unmatched.append(entry.get("title", ""))
            continue
        research_with_ids.append(
            {
                "category_label": entry.get("category_label", ""),
                "title": entry.get("title", ""),
                "description": entry.get("description", ""),
                "accomplishment_id": aid,
            }
        )

    # Map experience employer display names → employer_keys
    experience: dict[str, dict] = {}
    for emp_display, bullets in parsed["experience"].items():
        if not bullets:
            continue
        emp_key = employer_key_fn(emp_display)
        experience[emp_key] = {
            "bullets": [{"text": b, "accomplishment_ids": []} for b in bullets],
        }

    # Build the synthetic Document (no FK to a Job — these resumes weren't
    # tied to job postings tracked in this app).
    content_json = {
        "tagline": parsed["tagline"],
        "summary": parsed["summary"],
        "selected_research": research_with_ids,
        "experience": experience,
        "publications": [],
        "technical_skills": parsed["technical_skills"],
        "awards": parsed["awards"],
        "_ingested_from": str(docx_path),
    }

    doc = Document(
        job_id=None,
        doc_type=DocType.resume,
        name=f"Past resume — {company} — {title}".strip(" —"),
        content_markdown=None,
        content_docx_path=str(docx_path),
        content_json=content_json,
        version=1,
    )
    session.add(doc)
    await session.flush()

    job_context = {
        "job_id": None,
        "job_title": title,
        "company_name": company,
        "score_excerpt": None,
    }

    stats = {
        "doc_id": str(doc.id),
        "filename": docx_path.name,
        "company": company,
        "title": title,
        "research_inserted": 0,
        "research_unmatched": unmatched,
        "bullet_sets_inserted": 0,
        "skills_inserted": 0,
        "summary_inserted": False,
        "tagline_inserted": False,
    }

    # research_description rows
    for entry in research_with_ids:
        desc = (entry.get("description") or "").strip()
        if not desc:
            continue
        await _add_memory_row(
            session,
            entity_type="research_description",
            entity_key=entry["accomplishment_id"],
            doc_id=doc.id,
            user_text=desc,
            user_payload_json=None,
            job_context=job_context,
            source_text_hash=content_memory_service.compute_source_hash(
                "research_description",
                [entry["accomplishment_id"]],
                profile_data,
            ),
        )
        stats["research_inserted"] += 1

    # experience_bullets_set rows
    for emp_key, block in experience.items():
        bullets_payload = block["bullets"]
        if not bullets_payload:
            continue
        accomp_ids = [aid for b in bullets_payload for aid in (b.get("accomplishment_ids") or [])]
        await _add_memory_row(
            session,
            entity_type="experience_bullets_set",
            entity_key=emp_key,
            doc_id=doc.id,
            user_text=None,
            user_payload_json=bullets_payload,
            job_context=job_context,
            source_text_hash=content_memory_service.compute_source_hash(
                "experience_bullets_set",
                accomp_ids,
                profile_data,
            ),
        )
        stats["bullet_sets_inserted"] += 1

    # skill_bucket rows
    for bucket, value in parsed["technical_skills"].items():
        if not value:
            continue
        await _add_memory_row(
            session,
            entity_type="skill_bucket",
            entity_key=bucket,
            doc_id=doc.id,
            user_text=value,
            user_payload_json=None,
            job_context=job_context,
            source_text_hash=None,
        )
        stats["skills_inserted"] += 1

    # summary
    if parsed["summary"]:
        await _add_memory_row(
            session,
            entity_type="summary",
            entity_key="__scalar__",
            doc_id=doc.id,
            user_text=parsed["summary"],
            user_payload_json=None,
            job_context=job_context,
            source_text_hash=None,
        )
        stats["summary_inserted"] = True

    # tagline
    if parsed["tagline"]:
        await _add_memory_row(
            session,
            entity_type="tagline",
            entity_key="__scalar__",
            doc_id=doc.id,
            user_text=parsed["tagline"],
            user_payload_json=None,
            job_context=job_context,
            source_text_hash=None,
        )
        stats["tagline_inserted"] = True

    return stats


async def _add_memory_row(
    session,
    *,
    entity_type: str,
    entity_key: str,
    doc_id: uuid.UUID,
    user_text: str | None,
    user_payload_json: Any,
    job_context: dict,
    source_text_hash: str | None,
) -> None:
    row = ContentMemory(
        entity_type=entity_type,
        entity_key=entity_key,
        source_doc_id=doc_id,
        source_job_id=None,
        user_text=user_text,
        user_payload_json=user_payload_json,
        job_context=job_context,
        source_text_hash=source_text_hash,
        is_active=True,
    )
    session.add(row)
    await session.flush()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


async def main():
    docx_paths = sorted(p for p in RESUME_DIR.glob("*.docx") if not p.name.startswith("~$"))
    if not docx_paths:
        logger.warning("No .docx files found in %s", RESUME_DIR)
        return

    logger.info("Found %d resume(s) to ingest from %s", len(docx_paths), RESUME_DIR)

    async with async_session() as session:
        result = await session.execute(select(UserProfile).limit(1))
        profile = result.scalar_one_or_none()
        if profile is None:
            logger.error("No UserProfile in DB — run profile sync first.")
            return
        profile_data = profile.data

        # Keep base templates out of the ingest set.
        skipped: list[str] = []
        kept: list[Path] = []
        for p in docx_paths:
            n = p.name.lower()
            if "base_resume" in n or n.startswith("prateek_puri_cv_rand"):
                skipped.append(p.name)
                continue
            kept.append(p)

        logger.info("Skipping %d non-tailored file(s): %s", len(skipped), skipped)

        all_stats: list[dict] = []
        for path in kept:
            try:
                stats = await ingest_one(session, docx_path=path, profile_data=profile_data)
                if stats is None:
                    continue
                all_stats.append(stats)
                logger.info(
                    "INGESTED %s — research=%d (unmatched=%d) bullets=%d skills=%d summary=%s tagline=%s",
                    path.name,
                    stats["research_inserted"],
                    len(stats["research_unmatched"]),
                    stats["bullet_sets_inserted"],
                    stats["skills_inserted"],
                    stats["summary_inserted"],
                    stats["tagline_inserted"],
                )
                if stats["research_unmatched"]:
                    logger.info("  unmatched titles: %s", stats["research_unmatched"])
            except Exception:
                logger.exception("Failed to ingest %s", path.name)

        await session.commit()

    # Final summary
    total_research = sum(s["research_inserted"] for s in all_stats)
    total_bullets = sum(s["bullet_sets_inserted"] for s in all_stats)
    total_skills = sum(s["skills_inserted"] for s in all_stats)
    print()
    print("=" * 70)
    print(f"Ingested {len(all_stats)} resume(s)")
    print(f"  research_description rows : {total_research}")
    print(f"  experience_bullets_set rows: {total_bullets}")
    print(f"  skill_bucket rows         : {total_skills}")
    print(f"  summary rows              : {sum(1 for s in all_stats if s['summary_inserted'])}")
    print(f"  tagline rows              : {sum(1 for s in all_stats if s['tagline_inserted'])}")
    print("=" * 70)


if __name__ == "__main__":
    asyncio.run(main())
