"""initial schema

Revision ID: fbb3a138fc16
Revises: 
Create Date: 2026-03-15 20:02:24.214593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbb3a138fc16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('greenhouse', 'linkedin', 'ai_discovered', 'manual', name='job_source', create_constraint=True), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('new', 'interested', 'applied', 'interviewing', 'rejected', 'offer', 'archived', name='job_status', create_constraint=True), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('thumbs', sa.SmallInteger(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('search_profiles',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('locations', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('remote_ok', sa.Boolean(), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_profile',
    sa.Column('yaml_path', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_requirements',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('needs_resume', sa.Boolean(), nullable=False),
    sa.Column('needs_cover_letter', sa.Boolean(), nullable=False),
    sa.Column('needs_short_answers', sa.Boolean(), nullable=False),
    sa.Column('short_answer_prompts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('needs_video_interview', sa.Boolean(), nullable=False),
    sa.Column('needs_other', sa.Boolean(), nullable=False),
    sa.Column('other_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('documents',
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.Enum('resume', 'cover_letter', 'short_answer', 'other', name='doc_type', create_constraint=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_docx_path', sa.Text(), nullable=True),
    sa.Column('is_base_template', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_search_profile',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('search_profile_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_profile_id'], ['search_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'search_profile_id')
    )
    op.create_table('job_tags',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_tags')
    op.drop_table('job_search_profile')
    op.drop_table('documents')
    op.drop_table('application_requirements')
    op.drop_table('user_profile')
    op.drop_table('tags')
    op.drop_table('search_profiles')
    op.drop_table('jobs')
    # ### end Alembic commands ###
